### ISSUE TITLE
.net standard?

### ISSUE THREAD

**Issue by eaba** [developerslearnit/Paystack.Net.SDK#1]
Hello, does this sdk support .net standard?

**Comment by eaba** [comment]
I can confirm it doesn't! Please take the timeout to make this a .net standard 2
Your efforts are appreciated!

**Comment by developerslearnit** [comment]
Yes it doesn't support standard. But I will add the support soon. Thanks

**Comment by eaba** [comment]
@developerslearnit check my pull request

**Comment by developerslearnit** [comment]
Thanks. Merged

**Comment by eaba** [comment]
You welcomed

**Comment by developerslearnit** [comment]
I have to revert the merge because you just made it support .Net Standard and stop supporting .Net Framework. But I will update the source to support both before the end of the week. Thanks man

**Comment by eaba** [comment]
Sorry about that. Am working entirely on .netcore. Check my new pull, I have enabled support for net46 and made some adjustments...kindly review!!

**Comment by developerslearnit** [comment]
Please dont bother contributing again. I will add .netstandard support myself pretty soon.
<TargetFramework>netstandard2.0;net46</TargetFramework> wont work anywhere - It should be <TargetFrameworks>netstandard2.0;net46</TargetFrameworks>

Thanks

**Comment by developerslearnit** [comment]
I think you should always test after any modifications
